version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: postgres_productos
    restart: always
    environment:
      POSTGRES_DB: productosdb
      POSTGRES_USER: amelie
      POSTGRES_PASSWORD: 1234
    ports:
      - "5488:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  mongo:
    image: mongo
    container_name: mongo_productos
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongodata:/data/db

  redis:
    image: redis:alpine
    container_name: redis_productos
    restart: always
    ports:
      - "6379:6379"

volumes:
  pgdata:
  mongodata:
